// Generated by MambaScript 0.5.0 
var present = console.log; 
// Generated by MambaScript 0.5.0 
void function () {
  var a, b, c, cache$, cache$1, count, list, nonce;
  nonce = {};
  a = 0;
  a || (a = nonce);
  count = 0;
  list = [];
  list[++count] || (list[++count] = 1);
  present(list.length);
  'chained destructuring assignments';
  a = (cache$ = (cache$1 = [nonce = {}], c = cache$1['0'], cache$1), b = cache$[0], cache$)[0];
  present(a);
  present(b);
  present(c);
}.call(this);