#!/bin/sh
node_modules/.bin/pegjs --cache --export-var 'module.exports' <"src/grammar.pegjs" >"lib/parser.js.tmp" ;  mv "lib/parser.js.tmp" "lib/parser.js"
# tcoffee -c src/module.coffee -o lib
# tcoffee -c src/type-walker.coffee -o lib
tcoffee -c src/type-checker.coffee -o lib
# tcoffee -c src/types.coffee -o lib
# tcoffee -c src/reporter.coffee -o lib
# ./bin/tcoffee examples/assign.coffee
# ./bin/tcoffee examples/function.coffee
# echo '~~~~~~~~~~~~~~~~~~~~~~~'
node_modules/.bin/mocha --compilers coffee:./register -u tdd -R dot test/_setup.coffee test/type-checker.coffee
# ./bin/tcoffee scratch.coffee