// Generated by CoffeeScript 1.6.3
(function() {
  var X, Y, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  X = (function() {
    function X() {}

    X.prototype.f = function() {
      return console.log.apply(console, arguments);
    };

    return X;

  })();

  Y = (function(_super) {
    __extends(Y, _super);

    function Y() {
      _ref = Y.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Y.prototype.g = function() {
      return Y.__super__.g.apply(this, arguments).f("");
    };

    return Y;

  })(X);

}).call(this);
