// Generated by MambaScript 0.4.0 
var present = console.log; 
// Generated by MambaScript 0.4.0 
var MambaScript, runScripts;
MambaScript = require('./module');
MambaScript['eval'] = function (code, options) {
  if (null == options)
    options = {};
  if (null != options.bare)
    options.bare;
  else
    options.bare = true;
  if (null != options.optimise)
    options.optimise;
  else
    options.optimise = true;
  return eval(MambaScript.cs2js(code, options));
};
MambaScript.run = function (code, options) {
  if (null == options)
    options = {};
  options.bare = true;
  if (null != options.optimise)
    options.optimise;
  else
    options.optimise = true;
  return Function(MambaScript.cs2js(code, options))();
};
MambaScript.load = function (url, callback) {
  var xhr;
  xhr = window.ActiveXObject ? new window.ActiveXObject('Microsoft.XMLHTTP') : new XMLHttpRequest;
  xhr.open('GET', url, true);
  if ('overrideMimeType' in xhr)
    xhr.overrideMimeType('text/plain');
  xhr.onreadystatechange = function () {
    if (!(xhr.readyState === xhr.DONE))
      return;
    if (xhr.status === 0 || xhr.status === 200) {
      MambaScript.run(xhr.responseText);
    } else {
      throw new Error('Greetings from the MambaScript.load function in the browser.coffer file  Could not load ' + url);
    }
    if (callback)
      return callback();
  };
  return xhr.send(null);
};
runScripts = function () {
  var execute, index, mambas, s, scripts;
  scripts = document.getElementsByTagName('script');
  mambas = function (accum$) {
    for (var i$ = 0, length$ = scripts.length; i$ < length$; ++i$) {
      s = scripts[i$];
      if (!(s.type === 'text/mamba'))
        continue;
      accum$.push(s);
    }
    return accum$;
  }.call(this, []);
  index = 0;
  (execute = function () {
    var script;
    if (!(script = mambas[index++]))
      return;
    if (script.src) {
      return MambaScript.load(script.src, execute);
    } else {
      MambaScript.run(script.innerHTML);
      return execute();
    }
  })();
  return null;
};
if ('undefined' !== typeof addEventListener && null != addEventListener) {
  addEventListener('DOMContentLoaded', runScripts, false);
} else if ('undefined' !== typeof attachEvent && null != attachEvent) {
  attachEvent('onload', runScripts);
}
module.exports = MambaScript;
