// Generated by MambaScript 0.1.0 
var present = console.log; 
// Generated by MambaScript 0.1.0 
var Compiler, cscodegen, escodegen, escodegenFormat, ESMRewriter, ext, formatParserError, MambaScript, NewCoffeScript, Nodes, Optimiser, Parser, pkg, Preprocessor, reporter, TypeError, TypeWalker;
formatParserError = require('./helpers').formatParserError;
Nodes = require('./nodes');
Preprocessor = require('./preprocessor').Preprocessor;
Parser = require('./parser');
TypeWalker = require('./type-walker');
Optimiser = require('./optimiser').Optimiser;
Compiler = require('./compiler').Compiler;
reporter = require('./reporter');
TypeError = require('./type-helpers').TypeError;
cscodegen = function () {
  try {
    return require('cscodegen');
  } catch (e$) {
    return;
  }
}.call(this);
escodegen = function () {
  try {
    return require('escodegen');
  } catch (e$1) {
    return;
  }
}.call(this);
NewCoffeScript = require('coffeescript');
ESMRewriter = require('../utils/esm');
pkg = require('./../package.json');
escodegenFormat = {
  indent: {
    style: '  ',
    base: 0
  },
  renumber: true,
  hexadecimal: true,
  quotes: 'auto',
  parentheses: false
};
MambaScript = {
  MambaScript: MambaScript,
  Compiler: Compiler,
  Optimiser: Optimiser,
  Parser: Parser,
  Preprocessor: Preprocessor,
  Nodes: Nodes,
  NewCoffeScript: NewCoffeScript,
  VERSION: pkg.version,
  parse: function (coffee, options) {
    var e, parsed, preprocessed;
    if (null == options)
      options = {};
    try {
      preprocessed = Preprocessor.process(coffee, { literate: options.literate });
      parsed = Parser.parse(preprocessed, {
        raw: options.raw,
        inputSource: options.inputSource
      });
      TypeWalker.checkNodes(parsed);
      if (reporter.has_errors())
        throw new TypeError(reporter.report());
      return options.optimise ? Optimiser.optimise(parsed) : parsed;
    } catch (e$2) {
      e = e$2;
      if (e instanceof TypeError)
        throw e.message;
      if (!(e instanceof Parser.SyntaxError))
        throw e;
      throw new Error(formatParserError(preprocessed, e));
    }
  },
  compile: function (csAst, options) {
    return Compiler.compile(csAst, options).toBasicObject();
  },
  compileTypedToCS: function (csAst, options) {
    return cscodegen(csAst);
  },
  cs: function (csAst, options) {
  },
  jsWithSourceMap: function (jsAst, name, options) {
    var targetName;
    if (null == name)
      name = 'unknown';
    if (null == options)
      options = {};
    if (!(null != escodegen))
      throw new Error('escodegen not found: run `npm install escodegen`');
    if (!{}.hasOwnProperty.call(jsAst, 'type'))
      jsAst = jsAst.toBasicObject();
    targetName = options.sourceMapFile || options.sourceMap && options.output.match(/^.*[\\\/]([^\\\/]+)$/)[1];
    return escodegen.generate(jsAst, {
      comment: !options.compact,
      sourceMapWithCode: true,
      sourceMap: name,
      file: targetName || 'unknown',
      format: options.compact ? escodegen.FORMAT_MINIFY : null != options.format ? options.format : escodegenFormat
    });
  },
  jsEsm: function (jsAst, options) {
    var code;
    code = this.jsWithSourceMap(jsAst, null, options).code;
    return ESMRewriter(code);
  },
  js: function (jsAst, options) {
    return this.jsWithSourceMap(jsAst, null, options).code;
  },
  sourceMap: function (jsAst, name, options) {
    return this.jsWithSourceMap(jsAst, name, options).map;
  },
  cs2js: function (input, options) {
    var csAST, jsAST;
    if (null == options)
      options = {};
    if (null != options.optimise)
      options.optimise;
    else
      options.optimise = true;
    csAST = MambaScript.parse(input, options);
    jsAST = MambaScript.compile(csAST, { bare: options.bare });
    return MambaScript.js(jsAST, { compact: options.compact || options.minify });
  },
  smoothCompile: function (input, options) {
    var csAST, jsAST;
    if (null == options)
      options = {};
    if (null != options.optimise)
      options.optimise;
    else
      options.optimise = true;
    csAST = MambaScript.parse(input, options);
    jsAST = MambaScript.compile(csAST, { bare: true });
    return MambaScript.jsEsm(jsAST, { compact: options.compact || options.minify });
  },
  svelteCompile: function (input) {
    var options;
    options = {
      optimize: true,
      bare: true,
      header: true,
      compact: true
    };
    return this.cs2js(input, options);
  }
};
module.exports = MambaScript;
if (null != (null != require.extensions ? require.extensions['.node'] : void 0)) {
  MambaScript.register = function () {
    return require('./register');
  };
  for (var cache$ = [
        '.coffee',
        '.litcoffee',
        '.tcoffee',
        '.typed.coffee',
        '.mamba'
      ], i$ = 0, length$ = cache$.length; i$ < length$; ++i$) {
    ext = cache$[i$];
    if (null != require.extensions[ext])
      require.extensions[ext];
    else
      require.extensions[ext] = function () {
        throw new Error('Use MambaScript.register() or require the coffee-script-redux/register module to require ' + ext + ' files.');
      };
  }
}
