// Generated by KofuScript 0.0.3-alpha.7 
var present = console.log; 
// Generated by KofuScript 0.0.3-alpha.7 
var argv, child_process, coffeeBinary, CoffeeScript, compile, compileWithOriginalCoffee, fork, fs, path, runModule;
child_process = require('child_process');
fs = require('fs');
path = require('path');
CoffeeScript = require('./module');
runModule = require('./run').runModule;
module.exports = !(null != require.extensions['.coffee']);
argv = require('optimist').boolean('self').argv;
compile = function (module, filename, opts) {
  var csAst, input, js, jsAst;
  input = fs.readFileSync(filename, 'utf8');
  csAst = CoffeeScript.parse(input, opts);
  jsAst = CoffeeScript.compile(csAst);
  js = CoffeeScript.js(jsAst);
  return runModule(module, js, jsAst, filename);
};
compileWithOriginalCoffee = function (module, filename, opts) {
  var input, js, OriginalCoffee;
  if (null == opts)
    opts = {};
  OriginalCoffee = require('coffeescript');
  input = fs.readFileSync(filename, 'utf8');
  js = OriginalCoffee.compile(input, opts);
  return runModule(module, js, null, filename);
};
require.extensions['.typed.coffee'] = function (module, filename) {
  return compile(module, filename, {
    raw: true,
    typeCheck: true
  });
};
require.extensions['.coffee'] = function (module, filename) {
  if (argv.self) {
    return compile(module, filename, { raw: true });
  } else {
    return compileWithOriginalCoffee(module, filename, {
      raw: true,
      bare: argv.bare
    });
  }
};
require.extensions['.litcoffee'] = function (module, filename) {
  return compile(module, filename, {
    raw: true,
    literate: true
  });
};
require.extensions['.tcoffee'] = function (module, filename) {
  return compile(module, filename, {
    raw: true,
    typeCheck: true
  });
};
require.extensions['.kofu'] = function (module, filename) {
  return compile(module, filename, {
    raw: true,
    typeCheck: true
  });
};
fork = child_process.fork;
if (!fork.coffeePatched) {
  coffeeBinary = path.resolve('bin', 'kofu');
  child_process.fork = function (file, args, options) {
    if (null == args)
      args = [];
    if (null == options)
      options = {};
    if (in$(path.extname(file), [
        '.coffee',
        '.litcoffee',
        '.tcoffee',
        '.typed.coffee',
        '.kofu'
      ])) {
      if (!Array.isArray(args)) {
        args = [];
        options = args || {};
      }
      options.execPath || (options.execPath = coffeeBinary);
    }
    return fork(file, args, options);
  };
  child_process.fork.coffeePatched = true;
}
delete require.cache[__filename];
function in$(member, list) {
  for (var i = 0, length = list.length; i < length; ++i)
    if (i in list && list[i] === member)
      return true;
  return false;
}
