// Generated by CoffeeScript 2.0.0-beta8-dev
var ArrayInterface, ArrayType, checkAcceptableObject, clone, console, initializeGlobalTypes, NumberInterface, ObjectInterface, ObjectType, pj, Possibilites, render, reporter, rewrite, Scope, Type, TypeSymbol, VarSymbol;
console = {
  log: function () {
  }
};
pj = function () {
  try {
    return require('prettyjson');
  } catch (e$) {
    return;
  }
}.call(this);
render = function (obj) {
  if (null != pj)
    return pj.render(obj);
};
cache$ = require('./type-helpers');
clone = cache$.clone;
rewrite = cache$.rewrite;
reporter = require('./reporter');
NumberInterface = {
  toString: {
    name: 'function',
    _args_: [],
    returns: 'String'
  }
};
ArrayInterface = {
  length: 'Number',
  push: {
    name: 'function',
    _args_: ['T'],
    returns: 'void'
  },
  unshift: {
    name: 'function',
    _args_: ['T'],
    returns: 'void'
  },
  shift: {
    name: 'function',
    _args_: [],
    returns: 'T'
  },
  toString: {
    name: 'function',
    _args_: [],
    returns: 'String'
  }
};
ObjectInterface = function () {
  return {
    toString: {
      name: 'function',
      _args_: [],
      returns: 'String'
    },
    keys: {
      name: 'function',
      _args_: ['Any'],
      returns: { array: 'String' }
    }
  };
};
Type = function () {
  function Type() {
  }
  return Type;
}();
ObjectType = function (super$) {
  extends$(ObjectType, super$);
  function ObjectType(param$) {
    this.type = param$;
  }
  return ObjectType;
}(Type);
ArrayType = function (super$) {
  extends$(ArrayType, super$);
  function ArrayType(type) {
    this.array = type;
  }
  return ArrayType;
}(Type);
Possibilites = function (super$) {
  extends$(Possibilites, super$);
  function Possibilites(arr) {
    var i;
    if (null == arr)
      arr = [];
    for (var i$ = 0, length$ = arr.length; i$ < length$; ++i$) {
      i = arr[i$];
      this.push(i);
    }
  }
  return Possibilites;
}(Array);
checkAcceptableObject = function (left, right) {
  var r;
  if (null != (null != left ? left.base : void 0) && null != left.templates)
    left = left.base;
  console.log('checkAcceptableObject /', left, right);
  if (null != (null != right ? right.possibilities : void 0)) {
    for (var i$ = 0, length$ = right.possibilities.length; i$ < length$; ++i$) {
      r = right.possibilities[i$];
      checkAcceptableObject(left, r);
    }
    return;
  }
  if (left === 'Any')
    return;
  if (null != (null != left ? left.array : void 0)) {
    if (right.array instanceof Array) {
      return function (accum$) {
        for (var i$1 = 0, length$1 = right.array.length; i$1 < length$1; ++i$1) {
          r = right.array[i$1];
          accum$.push(checkAcceptableObject(left.array, r));
        }
        return accum$;
      }.call(this, []);
    } else {
      return checkAcceptableObject(left.array, right.array);
    }
  } else if (null != (null != right ? right.array : void 0)) {
    if (left === 'Array' || left === 'Any' || left === void 0) {
      return 'ok';
    } else {
      return reporter.add_error({}, 'object deep equal mismatch ' + JSON.stringify(left) + ', ' + JSON.stringify(right));
    }
  } else if (typeof left === 'string' && typeof right === 'string') {
    if (left === right || left === 'Any' || right === 'Any') {
      return 'ok';
    } else {
      return reporter.add_error({}, 'object deep equal mismatch ' + JSON.stringify(left) + ', ' + JSON.stringify(right));
    }
  } else if (typeof left === 'object' && typeof right === 'object') {
    return function (accum$) {
      var key, lval;
      for (key in left) {
        lval = left[key];
        if (right[key] === void 0 && ('undefined' !== typeof lval && null != lval)) {
          if (key === 'returns' || key === 'type')
            return;
          return reporter.add_error({}, "'" + key + "' is not defined on right");
        }
        accum$.push(checkAcceptableObject(lval, right[key]));
      }
      return accum$;
    }.call(this, []);
  } else if (left === void 0 || right === void 0) {
    return 'ignore now';
  } else {
    return reporter.add_error({}, 'object deep equal mismatch ' + JSON.stringify(left) + ', ' + JSON.stringify(right));
  }
};
initializeGlobalTypes = function (node) {
  node.addTypeObject('String', new TypeSymbol({
    type: 'String',
    'instanceof': function (expr) {
      return typeof expr.data === 'string';
    }
  }));
  node.addTypeObject('Number', new TypeSymbol({
    type: 'Number',
    'instanceof': function (expr) {
      return typeof expr.data === 'number';
    }
  }));
  node.addTypeObject('Boolean', new TypeSymbol({
    type: 'Boolean',
    'instanceof': function (expr) {
      return typeof expr.data === 'boolean';
    }
  }));
  node.addTypeObject('Object', new TypeSymbol({
    type: 'Object',
    'instanceof': function (expr) {
      return typeof expr.data === 'object';
    }
  }));
  node.addTypeObject('Array', new TypeSymbol({
    type: 'Array',
    'instanceof': function (expr) {
      return typeof expr.data === 'object';
    }
  }));
  node.addTypeObject('Undefined', new TypeSymbol({
    type: 'Undefined',
    'instanceof': function (expr) {
      return expr.data === 'undefined';
    }
  }));
  return node.addTypeObject('Any', new TypeSymbol({
    type: 'Any',
    'instanceof': function (expr) {
      return true;
    }
  }));
};
VarSymbol = function () {
  function VarSymbol(param$) {
    var cache$1;
    {
      cache$1 = param$;
      this.type = cache$1.type;
      this.implicit = cache$1.implicit;
    }
  }
  return VarSymbol;
}();
TypeSymbol = function () {
  function TypeSymbol(param$) {
    var cache$1;
    {
      cache$1 = param$;
      this.type = cache$1.type;
      this['instanceof'] = cache$1['instanceof'];
      this.templates = cache$1.templates;
    }
    if (null != this['instanceof'])
      this['instanceof'];
    else
      this['instanceof'] = function (t) {
        return t instanceof this.constructor;
      };
  }
  return TypeSymbol;
}();
Scope = function () {
  function Scope(param$) {
    if (null == param$)
      param$ = null;
    this.parent = param$;
    if (null != this.parent)
      this.parent.nodes.push(this);
    this.name = '';
    this.nodes = [];
    this._vars = {};
    this._types = {};
    this._this = {};
    this._returnables = [];
  }
  Scope.prototype.addReturnable = function (symbol, type) {
    return this._returnables.push(type);
  };
  Scope.prototype.getReturnables = function () {
    return this._returnables;
  };
  Scope.prototype.addType = function (symbol, type, templates) {
    return this._types[symbol] = new TypeSymbol({
      type: type,
      templates: templates
    });
  };
  Scope.prototype.addTypeObject = function (symbol, type_object) {
    return this._types[symbol] = type_object;
  };
  Scope.prototype.getType = function (symbol) {
    return (null != this._types[symbol] ? this._types[symbol].type : void 0) || void 0;
  };
  Scope.prototype.getTypeObject = function (symbol) {
    return this._types[symbol];
  };
  Scope.prototype.getTypeInScope = function (symbol) {
    return this.getType(symbol) || (null != this.parent ? this.parent.getTypeInScope(symbol) : void 0) || void 0;
  };
  Scope.prototype.addThis = function (symbol, type, implicit) {
    if (null == implicit)
      implicit = true;
    return this._this[symbol] = {
      type: type,
      implicit: implicit
    };
  };
  Scope.prototype.getThis = function (symbol) {
    return null != (null != this._this[symbol] ? this._this[symbol].type : void 0) ? null != this._this[symbol] ? this._this[symbol].type : void 0 : void 0;
  };
  Scope.prototype.addVar = function (symbol, type, implicit) {
    var n, obj, replacer, rewrite_to, T, t;
    if (null == implicit)
      implicit = true;
    console.log('addvar;', symbol, type);
    if (null != (null != type ? type.base : void 0)) {
      T = this.getTypeObject(type.base);
      if (!T)
        return;
      obj = clone(T.type);
      if (T.templates) {
        rewrite_to = type.templates;
        replacer = {};
        for (var i$ = 0, length$ = T.templates.length; i$ < length$; ++i$) {
          t = T.templates[i$];
          n = i$;
          replacer[t] = rewrite_to[n];
        }
        rewrite(obj, replacer);
      }
      return this._vars[symbol] = new VarSymbol({
        type: obj,
        implicit: implicit
      });
    } else {
      return this._vars[symbol] = new VarSymbol({
        type: type,
        implicit: implicit
      });
    }
  };
  Scope.prototype.getVar = function (symbol) {
    return null != (null != this._vars[symbol] ? this._vars[symbol].type : void 0) ? null != this._vars[symbol] ? this._vars[symbol].type : void 0 : void 0;
  };
  Scope.prototype.getVarInScope = function (symbol) {
    return this.getVar(symbol) || (null != this.parent ? this.parent.getVarInScope(symbol) : void 0) || void 0;
  };
  Scope.prototype.isImplicitVar = function (symbol) {
    return !!(null != this._vars[symbol] ? this._vars[symbol].implicit : void 0);
  };
  Scope.prototype.isImplicitVarInScope = function (symbol) {
    return this.isImplicitVar(symbol) || (null != this.parent ? this.parent.isImplicitVarInScope(symbol) : void 0) || void 0;
  };
  Scope.prototype.extendTypeLiteral = function (node) {
    var key, ret, type, val;
    switch (typeof node) {
    case 'object':
      if (node instanceof Array) {
        return function (accum$) {
          var i;
          for (var i$ = 0, length$ = node.length; i$ < length$; ++i$) {
            i = node[i$];
            accum$.push(this.extendTypeLiteral(i));
          }
          return accum$;
        }.call(this, []);
      } else {
        ret = {};
        for (key in node) {
          val = node[key];
          ret[key] = this.extendTypeLiteral(val);
        }
        return ret;
      }
    case 'string':
      type = this.getTypeInScope(node);
      switch (typeof type) {
      case 'object':
        return this.extendTypeLiteral(type);
      case 'string':
        return type;
      }
    }
  };
  Scope.prototype.checkAcceptableObject = function (left, right) {
    var l, r;
    l = this.extendTypeLiteral(left);
    r = this.extendTypeLiteral(right);
    return checkAcceptableObject(l, r);
  };
  Scope.prototype.checkFunctionLiteral = function (left, right) {
    var i, l_arg, r_arg;
    console.log('checkFunctionLiteral', left, right);
    left = this.extendTypeLiteral(left);
    right = this.extendTypeLiteral(right);
    if (left === void 0 || left === 'Any')
      return;
    if (null != left._args_)
      left._args_;
    else
      left._args_ = [];
    console.log(left);
    if ((null != left ? left._args_ : void 0) === void 0)
      return reporter.add_error(node, 'left is not arguments: ' + JSON.stringify(left) + ', ' + JSON.stringify(right));
    for (var i$ = 0, length$ = left._args_.length; i$ < length$; ++i$) {
      l_arg = left._args_[i$];
      i = i$;
      r_arg = right._args_[i];
      checkAcceptableObject(l_arg, r_arg);
    }
    if (right.returns !== 'Any')
      return checkAcceptableObject(left.returns, right.returns);
  };
  return Scope;
}();
module.exports = {
  checkAcceptableObject: checkAcceptableObject,
  initializeGlobalTypes: initializeGlobalTypes,
  VarSymbol: VarSymbol,
  TypeSymbol: TypeSymbol,
  Scope: Scope,
  ArrayType: ArrayType,
  ObjectType: ObjectType,
  Type: Type,
  Possibilites: Possibilites
};
function isOwn$(o, p) {
  return {}.hasOwnProperty.call(o, p);
}
function extends$(child, parent) {
  for (var key in parent)
    if (isOwn$(parent, key))
      child[key] = parent[key];
  function ctor() {
    this.constructor = child;
  }
  ctor.prototype = parent.prototype;
  child.prototype = new ctor;
  child.__super__ = parent.prototype;
  return child;
}
