// Generated by KofuScript 0.0.4-alpha.5 
var present = console.log; 
// Generated by KofuScript 0.0.4-alpha.5 
var count, currentNumber, stringParser, sum, total;
stringParser = require('arthur-pavlos-string-reversal');
total = 0;
count = 1;
while (count <= 10) {
  total += count;
  count += 1;
}
present(total);
sum = 0;
for (var i$ = 1; i$ <= 10; ++i$) {
  currentNumber = i$;
  sum += currentNumber;
}
present(sum);