// Generated by KofuScript 0.1.0-beta4 
var present = console.log; 
// Generated by KofuScript 0.1.0-beta4 
var charlie, count, currentNumber, stringParser, sum, total, val;
stringParser = require('arthur-pavlos-string-reversal');
charlie = require('b').charlie;
total = 0;
count = 1;
while (count <= 10) {
  total += count;
  count += 1;
}
present(total);
sum = 0;
for (var i$ = 1; i$ <= 10; ++i$) {
  currentNumber = i$;
  sum += currentNumber;
}
val = {
  key: 'value',
  mad: true,
  happy: true,
  cool: true
};
present(sum);
present(val);
module.exports = val;