// Generated by KofuScript 0.0.4-alpha.5 
var present = console.log; 
// Generated by KofuScript 0.0.4-alpha.5 
var charlie, count, currentNumber, stringParser, sum, total, val;
import _stringParser from 'arthur-pavlos-string-reversal'; 
 stringParser = _stringParser;
import { charlie as _charlie } from 'b'; 
 charlie = _charlie;
export charlie;
total = 0;
count = 1;
while (count <= 10) {
  total += count;
  count += 1;
}
present(total);
sum = 0;
for (var i$ = 1; i$ <= 10; ++i$) {
  currentNumber = i$;
  sum += currentNumber;
}
val = { key: 'value' };
present(sum);
export default val;