// Generated by KofuScript 0.1.0-beta4 
var present = console.log; 
// Generated by KofuScript 0.1.0-beta4 
var arthur, dominique, Person;
Person = function () {
  0;
  0;
  function Person(name, age) {
    this.name = name;
    this.age = age;
  }
  return Person;
}();
dominique = new Person('Dominique', '27');
arthur = 'arthur';
present(dominique);
present(dominique instanceof Person);
present(arthur instanceof Person);
present(5 === 6);
function isOwn$(o, p) {
  return {}.hasOwnProperty.call(o, p);
}
function extends$(child, parent) {
  for (var key in parent)
    if (isOwn$(parent, key))
      child[key] = parent[key];
  function ctor() {
    this.constructor = child;
  }
  ctor.prototype = parent.prototype;
  child.prototype = new ctor;
  child.__super__ = parent.prototype;
  return child;
}