// Generated by KofuScript 0.1.0-beta4 
var present = console.log; 
// Generated by KofuScript 0.1.0-beta4 
var c, Class, list, map, obj;
0;
0;
obj = { id: { value: '' } };
0;
map = function (list, fn) {
  var i;
  return function (accum$) {
    for (var i$ = 0, length$ = list.length; i$ < length$; ++i$) {
      i = list[i$];
      accum$.push(fn(i));
    }
    return accum$;
  }.call(this, []);
};
list = map([
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10
], function (n) {
  return 'i';
});
Class = function () {
  0;
  0;
  function Class(a) {
  }
  return Class;
}();
c = new Class(1);
function isOwn$(o, p) {
  return {}.hasOwnProperty.call(o, p);
}
function extends$(child, parent) {
  for (var key in parent)
    if (isOwn$(parent, key))
      child[key] = parent[key];
  function ctor() {
    this.constructor = child;
  }
  ctor.prototype = parent.prototype;
  child.prototype = new ctor;
  child.__super__ = parent.prototype;
  return child;
}